### ISSUE TITLE
[Device support] Goliathus Extended Chroma mousepad support

### ISSUE THREAD

**Issue by tYn0** [Vaskivskyi/ha-chroma#20]
### Anything you want to mention?

I have 3 Razer Chroma devices:

- Deathadder V2 Pro
- Blackwidow Chroma
- Goliathus Extended Chroma

Mouse and keyboard work great but mousepad does not work at all. Entity is created but changing light/brightness does nothing. When the integration starts mouse and keyboard are set to green but the color of the mousepad does not change. It is also not possible to change the color of the mousepad via Synapse
![image](https://user-images.githubusercontent.com/10382681/192808273-ce6a352b-0da2-4774-bd7f-ee42e592bd09.png)

### Your device model

Goliathus Extended Chroma

**Comment by Vaskivskyi** [comment]
Hello, @tYn0,

Thanks for your feedback! 👍🏻 

While integration is running, you cannot change settings from Synapse - that is normal since it allows only 1 active "controller" over RGB settings.

Does integration show any errors in the Home Assistant log? Does anything happen when you try to switch on/off the light responsible for the mousepad? Maybe some errors in the log after it?

**Comment by PecceG2** [comment]
Hi @Vaskivskyi , same problem with Goliathus Extended Chroma here. If i change the color of the "Chromalink" entity, pad automatically change the color but no change any another device (mouse, keyboard, microphone, headphones, etc.).
No logs from HASS.
It is as if the "ChromaLink" entity is actually the mousepad. Currently I use it like this, to change the color or turn on and off
the mousepad just i change the chromalink entity and everything works "as expected".

**Comment by Vaskivskyi** [comment]
Hey, @PecceG2,

Thanks for the intel! 👍🏻 

Unfortunately, that only means that Razer has added this mat in the wrong group for the API. Which means it cannot be fixed from the integration side. But this is good, it can be controlled, just with some "specifics"

**Comment by Vaskivskyi** [comment]
@tYn0,

Can you please check whether your Goliathus Extended Chroma can also be controlled via the `chromalink` light entity?

**Comment by tYn0** [comment]
Sorry for delayed answer. Yes using chromalink instead of the mousepad entity works
Thank you
