### ISSUE TITLE
[Bug] Can't connect SSL: BAD_SIGNATURE

### ISSUE THREAD

**Issue by PecceG2** [Vaskivskyi/ha-chroma#22]
### The problem

Hi, good morning! I tried to test the integration but I am running into this problem when trying to load the end device with SDK Server via hostname.
The integration does not connect with the client. SSL:BAD_SIGNATURE certificate error.

The server loads correctly if I do it from localhost, in fact, I use the API from Python to manage certain things and it is working fine. The problem only occurs from the HASS server.

Thanks in advance for any ideas or suggestions.

### Your device(s) with a problem

Ouroboros, Seiren Pro, Blackwidow Chroma, Huntsman Elite, Nari Ultimate, Kraken 7.1 V2, Goliathus Extended (XL)

### Firmware version

3.27.04

### Integration version with the issue

Latest (0.2.0)

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

OS 9.0 - Supervisor 2022.09.1 - Home Assistant 2022.10.1

### Is there anything useful in the logs?

```txt
Config entry 'Chroma' for chroma integration not ready yet: Cannot connect to host desktop-2skaf11.pecceg2.local:54236 ssl:True [[SSL: BAD_SIGNATURE] bad signature
```

**Comment by PecceG2** [comment]
The problem continues if I try to access via IP:
Reintentar la instalación: Cannot connect to host 10.10.0.20:54236 ssl:True [[SSL: BAD_SIGNATURE] bad signature (_ssl.c:997)]

**Comment by PecceG2** [comment]
Bueno, parece que el problema desaparece cuando actualizo Razer Synapse a la última versión.

Con las siguientes versiones, todo funciona actualmente: {"core":"3.28.01","device":"3.28.01","version":"3.28.01"}

Dejo abierta la sugerencia de agregar al README el hecho de que actualicen Razer Synapse a la última versión disponible para que todo funcione correctamente.

PD: Excelente complemento! Tengo muchas ganas de ver cómo la comunidad se une para agregar cosas como efectos y cosas por el estilo.

**Comment by PecceG2** [comment]
Well, it seems that the problem disappears when I update Razer Synapse to the latest version.

With the following versions, everything is currently working: {"core":"3.28.01","device":"3.28.01","version":"3.28.01"}

I leave it open for the suggestion to add to the README the fact that they update Razer Synapse to the latest version available so that everything works correctly.

PS: Excellent complement! I'm looking forward to seeing how the community gets on board to add things like effects and the like.

**Comment by Vaskivskyi** [comment]
Hello, @PecceG2,

Thanks for your feedback! 👍🏻 

That is strange, there are problems with the previous API versions, but everything could happen. I have definitely tested with some older ones but didn't keep track of the numbers.

I will add to the readme info about the possible problems with the older SDK versions
