### ISSUE TITLE
[Device support] Razer Huntsman Elite

### ISSUE THREAD

**Issue by PecceG2** [Vaskivskyi/ha-chroma#23]
### Anything you want to mention?

Works great with this device, and most probably works fine with Razer Hunstman devices as well (tournament edition & normal edition), they use the same controller for the RGB part with the difference of adding/removing certain keys.

### Your device model

Razer Huntsman Elite

### Firmware version

3.28.01

**Comment by Vaskivskyi** [comment]
Hey, @PecceG2,

What about other your devices, mentioned in #22 - do all of them work with the integration?

**Comment by PecceG2** [comment]
Hi @Vaskivskyi, I tried off and R-G-B switching with the following devices and work fine:
BlackWidow Chroma (V1, the first release of bw chroma keyboards)
Huntsman Elite
Kraken 7.1 V2
Goliathus Extended XL (With the clarification in #22 - "ChromaLink")

I have the Nari Ultimate headphones in boxes (right now I'm making an adaptation to add more battery), I'll connect them to the test power supply shortly and test them to see if they react correctly.

Regarding the Razer Ouroboros and the Razer Serien Pro, neither is reached by the project since although they have lights, they are not RGB and they do not seem to react when changing the RGB or turn on/off from HASS.

**Comment by PecceG2** [comment]
Edit: Nari Ultimate works fine!

**Comment by Vaskivskyi** [comment]
Great, thanks for the info! The devices are added to the compatible list.

P.S. Cannot Ouroboros and Serien Pro be controlled from Synapse?
