### ISSUE TITLE
[Device support] Razer Naga (Left-Handed Edition)

### ISSUE THREAD

**Issue by WolfwithSword** [Vaskivskyi/ha-chroma#30]
### Anything you want to mention?

A bit of a niche device but I would assume if this works, so would the non left-handed version. It's my only chroma enabled device that I can test and it seems to work just fine - I can adjust colour, brightness, toggle on and off, just about what you would expect.

The only issues I have may be me trying to test the limits of the SDK. For example, I made an automation to simulate a colour-transition effect based on a list of key colours. It doesn't seem to support the transition effect and instead just instantly changes to the colour. Would love to be able to retain or recreate effects for colour changing like in chroma studio. I wonder if like keyboard effects, if a custom chroma effect name can be passed to it?

~~The second is that if I lock my PC, the SDK stops all communication and it goes back to ChromaStudio's settings. When you log back in, it's a hit or miss if it auto re-enables. I often have to intervene for it to set back up. And if I restart the host PC, I need to reload the integration (or restart HA in one case where the integration would not reload).~~ A locked PC is not supported by Razer's software, so I doubt anything can be done here.

### Your device model

Razer Naga (Left Handed Edition)

### Firmware version

3.28.02

**Comment by Vaskivskyi** [comment]
Hello @WolfwithSword,

Thanks for your feedback! :+1:

There are more features coming to the integration soon. One of them will help perform colour transitions. Unfortunately, this work does take quite some time, so I cannot guarantee an exact timeframe yet. Saving and repeating effects are also planned.

Yes, unfortunately, locking PC is not supported by Synapse itself, regardless of how much users are asking Razer for this feature.

As for the stability of integration and automatic reconnect after the PC reboot - this is also a work in progress - so it will come to the integration 🙂

**Comment by Vaskivskyi** [comment]
PR #32 will add your device to the supported list and will close this issue. As I have mentioned before, the features in question are already planned and will be released in the following integration releases
