### ISSUE TITLE
[Bug] integration requires a reboot of the Home Assistant

### ISSUE THREAD

**Issue by KaportsevIA** [Vaskivskyi/ha-chroma#37]
### The problem

After the computer with connected Razer Chrome devices is offline for a while, the integration requires restarting the Home Assistant, after the computer appears on the HA network. Devices switch to the unavailable status. And when you restart the Chrome integration, it requires "Restart the Home Assistant to complete the integration reboot".

### Firmware version

3.29.00

### Integration version with the issue

3,29,00

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

Supervisor 2022.10.2

**Comment by Vaskivskyi** [comment]
Hello, @KaportsevIA,

Thanks for your feedback! :+1:

I will check, why Chroma cannot restart without rebooting HA. I will let you know whether any more info is needed from your side or when the bug fix will be released.

**Comment by Arnavisca** [comment]
Hello.
Some progress? I have the same problem.

**Comment by Vaskivskyi** [comment]
Hey,

There are quite several problems with keeping a connection between HA and Synapse API. Unfortunately, Synapse is not the most stable software ever.

But the work is still in progress and I am expecting to make Chroma integration more stable and user-friendly.

**Comment by Arnavisca** [comment]
OK. Thanks for the reply.

**Comment by jack5mikemotown** [comment]
> But the work is still in progress and I am expecting to make Chroma integration more stable and user-friendly.

What's the solution in the meantime, it the only way for now to restart HA every time you want to reestablish connection with the device?

**Comment by xTim18** [comment]
Same issue on my side. Any solution or work around by now?

**Comment by Vaskivskyi** [comment]
Hello. Unfortunately, I had no free time to work on the Chroma integration before. I will try to solve the issues reported by the users shortly

**Comment by Vaskivskyi** [comment]
Please, check the new version `0.3.0`. The integration should now properly reconnect to your Chroma devices by itself. Also, you should be now able to reload the integration without a need to reload HA

**Comment by xTim18** [comment]
> Please, check the new version `0.3.0`. The integration should now properly reconnect to your Chroma devices by itself. Also, you should be now able to reload the integration without a need to reload HA

Great so see progress is made on this, but unfortunatley after some testing it does not seem to change anything for me yet. Updated the HACS integration, anything else I need to do?
