### ISSUE TITLE
Dependency Error - [Bug] 

### ISSUE THREAD

**Issue by SQLSamulski** [Vaskivskyi/ha-chroma#50]
### The problem

Logger: homeassistant.util.package
Source: util/package.py:107
First occurred: 10:47:11 AM (3 occurrences)
Last logged: 10:47:19 AM

Unable to install package aiochroma==0.1.1: ERROR: Cannot install aiochroma==0.1.1 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.0 -> 23.0.1 [notice] To update, run: pip install --upgrade pip

### Your device(s) with a problem

Chroma Integration is "half configured" and cannot delete due to missing dependency

### Firmware version

Can't reach this

### Integration version with the issue

0.2.1

### Method of the integration installation

HACS

### What version and type of Home Assistant installation do you use

2023.3.6

**Comment by Vaskivskyi** [comment]
Hello,

@SQLSamulski,

I am sorry for the issue you have. Please, update Chroma integration to the latest version (0.2.2) already available via HACS - the issue with dependencies is fixed in this release
